spring.application.name=orm-learn

# Spring
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Hibernate connection for print SQL Input and Output
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.type.descriptor.sql=trace

# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=rt67Tv99#i

# Hibernate configuration
spring.jpa.hibernate.dll-auto=validate
spring.jpa.properties.hibernate.dialate=org.hibernate.dilect.MySQL5Dialect